# Generated by Django 5.2.8 on 2025-12-28 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('plot', 'Plot'), ('flat', 'Flat'), ('house', 'House')], max_length=10)),
                ('requirement', models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')])),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
