# Generated by Django 5.2.8 on 2026-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default='eg@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(default='9995559990', max_length=11),
        ),
    ]
