# Generated by Django 5.2.8 on 2026-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_enquiry_email_enquiry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(default='00000', max_length=11),
        ),
    ]
