# Generated by Django 5.2.8 on 2026-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_enquiry_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='agent_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='visiting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
