# Generated by Django 5.2.8 on 2026-02-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_property_property_type_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('flat', 'Flat'), ('house', 'House')], max_length=10),
        ),
    ]
