# Generated by Django 5.2.8 on 2026-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='buyer_visited',
            field=models.BooleanField(default=False),
        ),
    ]
