# Generated by Django 5.2.8 on 2026-02-23 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_alter_payment_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='listing.enquiry'),
        ),
    ]
