# Generated by Django 5.2.8 on 2026-02-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0020_alter_payment_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to='listing.property'),
        ),
    ]
