# Generated by Django 5.2.8 on 2026-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_alter_enquiry_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='buyer_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
